- .gitignore
- README.md
- package.json
- partials/message.html
- partials/tags.html
- test/spec/asyncapi.yml
- add support for tags  externalDocs url and tags in general in messages
- added one additional if in tag macro to not get empty div in case of no tags
- added some development help
I choose to not use externalDocs.description as it would complicate first iteration a lot. There are too many combinations available in case if we want to support `externalDocs.description` because we would have to take into account that user would like to use `description` like `Click here for more info` to the tag could not be clickable link but somehow the text inside tooltip.
Now, in case `url` is provided, the `name` of the tag becomes a hyperlink as discussed in the issue.
To test it with your spec just run `ag <your-asyncapi-file> https://github.com/derberg/html-template#support-tags` …
> feat: add support for tags  externalDocs url

- partials/schema-prop.html
- test/spec/asyncapi.yml
According to the JSON Schema, and our parser (https://github.com/asyncapi/parser-js/blob/master/lib/models/schema.js#L195), `additionalProperties` and `additionalItems` are allowed to be boolean or an object, never an array - and yet the HTML template handles this case.
Can anyone confirm this, or have I misunderstood somewhere along the way? 
I noticed this while exploring another issue (https://github.com/asyncapi/html-template/issues/11), but wanted to sense check.
> refactor: remove unnecessary handling of isArray case

- partials/schema-prop.html
Now that https://github.com/asyncapi/parser-js/issues/78#issuecomment-620469576 has been resolved, and deprecated() is available, flag properties that have the deprecated attribute.
**Note** I'm not sure how to show that we now have a dependency on parser-js > 0.18.3?
```
cb_hardware_version:
type: string
deprecated: true
```
is displayed as:
> feat: Flag deprecated properties

- .tp-config.json
- filters/all.js
- package-lock.json
- package.json
- partials/schema-prop.html
- partials/servers.html
- use generic filters library
- modify and cleanup of local filters for new testable style
- adjust template to use new filters
See also https://github.com/asyncapi/generator/issues/212
> feat: use new generic filters

- partials/example.html
- template/css/main.css
Possible fix for #23 
I need help from someone.
> feat: make payload example collapsible

- partials/content.html
- partials/message.html
- partials/messages.html
- partials/sidebar.html
> feat: list all messages in sidebar

- .github/workflows/pull-request-testing.yml
- filters/all.js
- package-lock.json
- package.json
- test/all.contain_no_tag.test.js
- test/all.contain_tags.test.js
- test/all.is_expandable.test.js
- test/all.non_parser_extensions.test.js
After adding some new code to `all.js` and as per @derberg proposed I thought it'd be better to add some tests in order to not break the existing features.
I just incorporated "Ava" as it's the one used in the generator-filters repository, which seems to work well.
The changes made to `isExpandable` (`(typeof obj.type === "function" && obj.type() === "object")`) are to first check if the object has defined a `type` function, otherwise, it throws an error. But it seems that there are some other parts of an AsyncApi object that might not have `type` defined but some of the other functions that are there checked.
> chore: add all filters tests

- README.md
- filters/all.js
- package-lock.json
- package.json
- partials/operations/by_tags.html
- partials/operations/by_tags_no_root.html
- partials/sidebar.html
- test/all.contain_no_tag.test.js
- test/all.contain_tags.test.js
- test/all.operations_tags.test.js
- test/spec/asyncapi.yml
Implements https://github.com/asyncapi/html-template/issues/42.
`all.js` now defines a function `operationsTags` to get subscription/publish operations tags and use them to build the sidebar.
New functionality available under `sidebarOrganization` param with `byTagsNoRoot` value
> feat: Add flag to use operations tags instead of root tags for the sidebar

- partials/schema-prop.html
Fixes a bug happening when `prop.items()` returns undefined or null.
> fix: bug in array items

- partials/introduction.html
- partials/message.html
2 Birds, One stone!
This PR solves 2 issues
Added mailto to the href for mail support as mentioned in issue #56
Wrapped msg.payload() within an if statement as in issue #55
Resolves #55 AND #56
> fix: Support for empty payload and mailto attribute for contact email

- hooks/01_removeNotRelevantParts.js
- package-lock.json
- package.json
Pulls in `rimraf` module which is a stable recursive directory delete that can replace `fs.rmdir` until it becomes stable.
Resolves #78
> fix: support node 12.2.0 when using singleFile parameter

- partials/servers.html
- test/spec/asyncapi.yml
- Default to Authorization when auth type is http.
Fixes #28
> fix: Default to Authorization header when auth type is http

- filters/all.js
- test/all.is_expandable.test.js
The scalar types are coming with an empty object in `patternProperties()` thus triggering the `isExpandable` filter. I changed the condition to verify if the object returned by `patternProperties()` is empty or not. It may be valid to also check why they are coming with it in the first place.
**Related issue**
Resolves #50
> fix: scalar types should not have a chevron icon indicating you can expand it

- partials/schema-prop.html
- partials/type.html
- Fix broken support for oneOf anyOf allOf in array items
Fixes https://github.com/asyncapi/playground/issues/36 https://github.com/asyncapi/generator/issues/427
this is how it is displayed now
for such a spec
```
asyncapi: 2.0.0
info:
title: Test MQTT API
version: '1.0.0'
description: |
Test
defaultContentType: application/json
channels:  
foo/bar:
description: Test MQTT operation
publish:
message:
$ref: '#/components/messages/testMessage'
components:
messages:
testMessage:
contentType: application/json
payload:
$ref: "#/components/schemas/mainSchema"
schemas:
oneOfSchema:
type: object
properties:
foo:
type: number
format: float	
oneOfSchema2:
type: object
properties:
foo:
type: number
format: float	    
mainSchema:
type: object
properties: …
```
> feat: display schema uid and broken support for oneOf anyOf allOf in array items

- hooks/generatePdf.js
- add args to puppeteer to make pdf generation work in docker
Fixes https://github.com/asyncapi/html-template/issues/112
> fix: add args to puppeteer to make pdf generation work in docker

- partials/schema-prop.html
- mark required props in object in array
See also https://github.com/asyncapi/playground/issues/43
> fix: mark required props in object in array

- partials/schema-prop.html
- array with an array of items throws an error and only object is supported
I think I introduced the bug when I was adding support for circular refs. Good thing is though that we now regularly extend our dummy yaml file with more cases that need to be covered in tools -> https://github.com/asyncapi/generator/pull/443
Fixes https://github.com/asyncapi/generator/issues/441
> fix: array with array of items throws error and only object is supported

- README.md
- package.json
- partials/message.html
> feat: display correlationId to the rendered html

- partials/servers.html
- partials/sidebar.html
- template/css/main.css
Due to the migration from tailwind v0.x to v2.x changed its default styling for lists ([see here](https://www.tailwindcss.cn/docs/upgrading-to-v1/#8-remove-any-usage-of-list-reset)). This does not affect the UI in general (like the `<ul>`in the sidebar), because list items were already rendered without bullet points. However, source from markup code should be displayed with bullet points and be intended.
Resolves #142
> fix: rendering of list items in markdown

- .github/workflows/pr-testing-with-generator.yml
- .gitignore
- package-lock.json
- package.json
- template/css/main.min.css
- as a result of this PR we will treat generated css file like any other additional release asset, like bundle.js for the parser for example, or generated ts types for the parser. So this is basically something that always needs to be part of the package, and not that it is generated always during the installation
- postcss cli moved to dev deps and they do not need to be there in the production dependencies
- some basic primitive checks on CI so these failures do not happen in the future. We just perform dummy generation there to make sure it doesn't fail. Generator is installed during the CI run, it is not part of the devDeps because we install HTML template with `NODE_ENV=production` to mimic real template usage in production env, so the generator would not be available …
> fix: change css processing from installation to npm publishing

- template/css/main.css
- Fix list styling for ol and ul
- Fix bold styling
- https://github.com/asyncapi/html-template/issues/162
- https://github.com/asyncapi/html-template/issues/142
> fix: rendering of list items in markdown and bold

- partials/message.html
- partials/operation.html
- partials/operations.html
- partials/protocols.html
- partials/servers.html
Here is the result with the dummy file on asyncapi/generator#556
Channel and operation bindings : 
By the way, it seems that settings bindings on a channel is not handle by the parser (see the dummy file content and the related generation)
For message bindings : 
Resolves #25
> feat: display protocol bindings on server, channel, operation, message

- partials/extensions.html
- partials/message.html
- partials/schema-prop.html
- template/css/main.css
- template/css/main.min.css
- refactor current extensions rendering support to have it as reusable macro
- for now support it only on a message, other can come when others need it, I needed it for message only
- modified css to make sure dump of long text in pre code is wrapped
> feat: support spec extension rendering for messages

- partials/protocols.html
stuff like this get very long and run outside the container:
```yml
bindings:
kafka:  
x-key.subject.name.strategy:
type: string
description: |
We use the **RecordNameStrategy** to infer the messages schema.
Use `io.confluent.kafka.serializers.subject.RecordNameStrategy` for your consumer.
x-value.subject.name.strategy:
type: string
description: |
We use the **RecordNameStrategy** to infer the messages schema.
Use `io.confluent.kafka.serializers.subject.RecordNameStrategy` for your consumer.
```
> fix: wrap long object dump when rendering binding info

- hooks/01_removeNotRelevantParts.js
As in title. In the [server-api](https://github.com/asyncapi/server-api) project we have problem when someone pass `singleFile` parameter and due to fact that given files are removed in async mode (without waiting) we can end up with situation when someone will get generated template with these files.
> fix: move to synchronouse deletion of unnecessary files

- README.md
Previously the README contained instructions on how to use the template using Generator. I have added instructions on an alternate way of using the template using the AsyncAPI CLI.
Tagging @derberg
> docs: add instructions for using AsyncAPI CLI

- package-lock.json
- package.json
This PR locks the react components to not use the `1.0.0-next.48` version which contains breaking changes for this library.
Fixes #438
> fix: lock react components version

- package.json
- scripts/copy-sources.js
- scripts/transpile.js
- Added the transpile scripts that creates `__transpiled ` folder in the root directory
- Modify the `prepublishOnly` scripts that ensures transpilation runs before publishing
Fixes #558
> feat: add scripts that on release will publish transpiled template to npm

- .npmignore
- package.json
- scripts/transpile.js
- Include `__transpiled`  folder in publishing of the package 
- Have modified the `.npmignore` for including the transpiled folder
Resolves #575
> feat: include `__transpiled` folder in the package

- hooks/99_generatePdf.js
- package-lock.json
- package.json
Reverts asyncapi/html-template#668
It should not be done without getting https://github.com/asyncapi/html-template/pull/615 first done.
we can upgrade puppeteer because generator v2 do not support old node - but we cannot do it without first updating template that it no longer supports old generator v1 - this must be done as a major release
fyi @bakasmarius
> fix: revert update puppeteer to 23.2.0

- hooks/01_removeNotRelevantParts.js
> fix: add a check to fix the generation failed in the parallel execution
